# Generated by Django 3.0.8 on 2020-07-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_auto_20200712_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
