# Generated by Django 3.0.8 on 2020-07-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_auto_20200712_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking_history',
            options={'verbose_name': '', 'verbose_name_plural': 'Booking History'},
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='seat_no',
            field=models.IntegerField(null=True),
        ),
    ]
